obj-m += mymmap.o mymod.o 0mymod.o 1mymod.o 2mymod.o 3mymod_gpiolib_devicetree.o 4mymod_pc.o 6mymod_int.o timer_mutex_read.o # 7mymod_task.o 3mymod_gpiolib_devicetree.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

