obj-m += 0mymod.o 1mymod.o 2mymod.o 3mymod_gpiolib_devicetree.o 4mymod_pc.o 6mymod_int.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

